import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, Loader2, X, Zap, GraduationCap, Stethoscope, Briefcase, FlaskConical, BookOpen } from 'lucide-react';
import { generateFullMap, detectDomain } from '../services/gemini';
import { aiMemory } from '../services/aiMemory';
import type { UserLevel } from '../services/aiMemory';
import type { ThoughtNode, NodeType } from '../types';
import { cn } from '../lib/utils';

interface ThinkForMeModalProps {
  isOpen: boolean;
  onClose: () => void;
  onMapGenerated: (nodes: ThoughtNode[], connections: { fromId: string; toId: string }[]) => void;
  activeProjectId: string;
}

const DOMAIN_OPTIONS = [
  { id: 'school', label: 'School', icon: BookOpen, color: 'text-blue-500' },
  { id: 'engineering', label: 'Engineering', icon: Zap, color: 'text-yellow-500' },
  { id: 'medical', label: 'Medical', icon: Stethoscope, color: 'text-red-500' },
  { id: 'business', label: 'Business', icon: Briefcase, color: 'text-green-500' },
  { id: 'research', label: 'Research', icon: FlaskConical, color: 'text-purple-500' },
];

const LEVEL_OPTIONS: { id: UserLevel; label: string }[] = [
  { id: 'beginner', label: 'Beginner' },
  { id: 'intermediate', label: 'Intermediate' },
  { id: 'advanced', label: 'Advanced' },
];

const EXAMPLES = [
  "Photosynthesis", "Machine Learning", "Cardiovascular System",
  "Project Management", "Quantum Mechanics", "Business Strategy",
  "French Revolution", "Neural Networks", "Cell Biology"
];

interface VoiceMapNode { title: string; children: VoiceMapNode[] }

function flattenMapToNodes(
  root: VoiceMapNode,
  parentId: string | null,
  projectId: string,
  allNodes: ThoughtNode[],
  allConnections: { fromId: string; toId: string }[],
  depth: number = 0,
  index: number = 0
) {
  const id = `tfm-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  const angle = (2 * Math.PI * index) / Math.max((root.children?.length || 1), 1);
  const radii = [0, 22, 40];
  const cx = 50, cy = 45;
  const r = radii[Math.min(depth, 2)];

  const node: ThoughtNode = {
    id,
    type: depth === 0 ? 'sphere' : 'concept',
    title: root.title,
    description: `Generated by AI Think-For-Me`,
    tags: [depth === 0 ? 'root' : 'ai-generated'],
    x: Math.max(5, Math.min(90, cx + r * Math.cos(angle - Math.PI / 2))),
    y: Math.max(5, Math.min(88, cy + r * Math.sin(angle - Math.PI / 2))),
    projectId,
    status: 'active',
  };

  allNodes.push(node);
  if (parentId) {
    allConnections.push({ fromId: parentId, toId: id });
  }

  root.children?.forEach((child, i) => {
    flattenMapToNodes(child, id, projectId, allNodes, allConnections, depth + 1, i);
  });
}

export function ThinkForMeModal({ isOpen, onClose, onMapGenerated, activeProjectId }: ThinkForMeModalProps) {
  const [topic, setTopic] = useState('');
  const [selectedDomain, setSelectedDomain] = useState('general');
  const [selectedLevel, setSelectedLevel] = useState<UserLevel>(aiMemory.get().userLevel);
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState('');

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setIsGenerating(true);

    // Auto-detect domain if not manually set
    const autoDomain = selectedDomain === 'general' ? detectDomain(topic) : selectedDomain;
    setProgress('Analyzing topic...');

    await new Promise(r => setTimeout(r, 400));
    setProgress('Generating mind map structure...');

    const result = await generateFullMap(topic.trim(), autoDomain, selectedLevel);

    setProgress('Placing nodes...');
    await new Promise(r => setTimeout(r, 300));

    if (result?.root) {
      const newNodes: ThoughtNode[] = [];
      const newConnections: { fromId: string; toId: string }[] = [];
      flattenMapToNodes(result.root, null, activeProjectId, newNodes, newConnections);
      onMapGenerated(newNodes, newConnections);
      aiMemory.recordNodeExpansion(topic, autoDomain as any);
    }

    setIsGenerating(false);
    setProgress('');
    onClose();
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[300] flex items-center justify-center p-4"
        onClick={e => { if (e.target === e.currentTarget) onClose(); }}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.9, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.9, y: 20 }}
          transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          className="bg-surface border-2 border-outline rounded-2xl shadow-[8px_8px_0px_0px_var(--color-outline)] w-full max-w-lg"
        >
          {/* Header */}
          <div className="flex items-center justify-between p-5 border-b border-outline">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-white" />
              </div>
              <div>
                <h2 className="text-sm font-black uppercase tracking-tight text-on-surface">Think For Me</h2>
                <p className="text-[9px] text-on-surface-variant uppercase font-bold tracking-widest">AI Full Map Generator</p>
              </div>
            </div>
            <button onClick={onClose} className="w-8 h-8 rounded-lg flex items-center justify-center text-on-surface-variant hover:bg-surface-container-high transition-colors">
              <X className="w-4 h-4" />
            </button>
          </div>

          <div className="p-5 space-y-5">
            {/* Topic Input */}
            <div>
              <label className="block text-[9px] font-black uppercase tracking-widest text-on-surface-variant mb-2">
                Topic / Subject / Concept
              </label>
              <input
                value={topic}
                onChange={e => setTopic(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleGenerate()}
                placeholder="e.g. Machine Learning, Cardiovascular System..."
                className="w-full bg-surface-container-low border-2 border-outline rounded-xl px-4 py-3 text-sm text-on-surface outline-none focus:border-primary transition-colors font-medium"
              />
              {/* Example chips */}
              <div className="flex flex-wrap gap-1.5 mt-2">
                {EXAMPLES.slice(0, 5).map(ex => (
                  <button
                    key={ex}
                    onClick={() => setTopic(ex)}
                    className="text-[8px] px-2 py-0.5 bg-surface-container-high border border-outline rounded-full font-bold text-on-surface-variant hover:bg-primary hover:text-white hover:border-primary transition-all"
                  >
                    {ex}
                  </button>
                ))}
              </div>
            </div>

            {/* Domain Selection */}
            <div>
              <label className="block text-[9px] font-black uppercase tracking-widest text-on-surface-variant mb-2">
                Domain
              </label>
              <div className="flex gap-2 flex-wrap">
                {DOMAIN_OPTIONS.map(d => {
                  const Icon = d.icon;
                  return (
                    <button
                      key={d.id}
                      onClick={() => setSelectedDomain(d.id)}
                      className={cn(
                        "flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-[9px] font-black uppercase tracking-wider transition-all",
                        selectedDomain === d.id
                          ? "bg-primary border-primary text-white"
                          : "bg-surface border-outline text-on-surface-variant hover:border-primary"
                      )}
                    >
                      <Icon className={cn("w-3 h-3", selectedDomain === d.id ? "text-white" : d.color)} />
                      {d.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Level Selection */}
            <div>
              <label className="block text-[9px] font-black uppercase tracking-widest text-on-surface-variant mb-2">
                Knowledge Level
              </label>
              <div className="flex gap-2">
                {LEVEL_OPTIONS.map(l => (
                  <button
                    key={l.id}
                    onClick={() => setSelectedLevel(l.id)}
                    className={cn(
                      "flex-1 py-1.5 rounded-lg border text-[9px] font-black uppercase tracking-wider transition-all",
                      selectedLevel === l.id
                        ? "bg-on-surface border-on-surface text-surface"
                        : "bg-surface border-outline text-on-surface-variant hover:border-primary"
                    )}
                  >
                    {l.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Generate Button */}
            <button
              onClick={handleGenerate}
              disabled={!topic.trim() || isGenerating}
              className="w-full py-3.5 bg-primary text-white font-black text-[10px] uppercase tracking-widest rounded-xl hover:bg-primary/90 transition-all shadow-[4px_4px_0px_rgba(37,99,235,0.3)] disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  {progress || 'Generating...'}
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Generate Complete Mind Map
                </>
              )}
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
